---
title: '**TFM: Feature Engineering**'
author: '*Roberto Jesús Alcaraz Molina*'
date: "14/04/2021"
output:
  pinsurance_document:
    toc: T
    fig_caption: yes
header-includes: 
- \usepackage{float}
- \usepackage{amsbsy}
- \usepackage{amsmath}
- \usepackage{graphicx}
- \usepackage{subfig}
- \usepackage{booktabs}
---

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = F, 
                      message = FALSE,
                      fig.pos="H", 
                      fig.align="center",
                      fig.width=15,
                      cache=FALSE, error = TRUE)
```

```{r, echo = F}
# install.packages("pacman")
pacman::p_load(tidyverse, tidymodels, workflowsets, tune, patchwork, FactoMineR)
theme_set(theme_bw())

# Models packages
pacman::p_load(ranger)
```

# Necessary code
```{r}
insurance <- readRDS("insurance.RDS")
insurance_accident <- readRDS("insurance_accident.RDS")
insurance_caidas <- readRDS("insurance_caidas.RDS")


set.seed(123)

insurance_split <- initial_split(insurance, 
                                 prop = 0.7, 
                                 strata = accident)
insurance_train <- training(insurance_split)
insurance_test <- testing(insurance_split)

# Recipe
rec <- 
  recipe(accident ~ period + cover + sex + smoker + good_health + actuarial_age + exp + duration + capital + IMC, data = insurance_train)

# Model
glm_model <- logistic_reg() %>%
  set_engine("glm")

# Workflow
glm_workflow <- workflow() %>%
  add_model(glm_model) %>%
  add_recipe(rec)
```

# Croos-validation

```{r}
set.seed(23)
insurance_folds <- vfold_cv(insurance_train, v = 5,
                            strata = accident)
```

```{r}
keep_pred <- control_resamples(save_pred = TRUE, 
                               save_workflow = TRUE)

set.seed(23)
glm_res <- glm_workflow %>%
  fit_resamples(
    resamples = insurance_folds,
    control = keep_pred
  )

collect_metrics(glm_res)
```

Let's try now with the modified recipe:

```{r}
rec <- rec %>%
  themis::step_downsample(accident) %>%
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_log(capital, IMC, base = 10)

# Model
glm_model <- logistic_reg() %>%
  set_engine("glm")

# Workflow
glm_workflow <- workflow() %>%
  add_model(glm_model) %>%
  add_recipe(rec)
```

```{r}
set.seed(23)
glm_res <- glm_workflow %>%
  fit_resamples(
    resamples = insurance_folds,
    control = keep_pred,
    metrics = metric_set()
  )

glm_res

collect_metrics(glm_res)
```


# Creating different sets of predictors

```{r}
set_predictors <- list(
  # original
  base = accident ~ period + cover + sex + smoker + good_health + actuarial_age + exp + duration + capital + IMC,
  
  # only numerical variables
  only_num = accident ~ actuarial_age + exp + duration + capital + IMC,
  
  # sus_age instead of actuarial age
  suscription = accident ~ period + cover + sex + smoker + good_health + sus_age + exp + duration + capital + IMC,
  
  # int duration
  dur_cat = accident ~ period + cover + sex + smoker + good_health + actuarial_age + exp + duration_cat + capital + IMC,
  
  # capital factor 1 instead of capital
  cap_1 = accident ~ period + cover + sex + smoker + good_health + actuarial_age + exp + duration + capital_factor_1 + IMC,
  
  # capital factor 2 instead of capital
  cap_2 = accident ~ period + cover + sex + smoker + good_health + actuarial_age + exp + duration + capital_factor_2 + IMC,
  
  # capital factor 3 instead of capital
  cap_3 = accident ~ period + cover + sex + smoker + good_health + actuarial_age + exp + duration + capital_factor_3 + IMC,
  
  # IMC factor 1 instead of IMC
  IMC_1 = accident ~ period + cover + sex + smoker + good_health + actuarial_age + exp + duration + capital + IMC_factor_1,
  
  # IMC factor 2 instead of IMC
  IMC_2 = accident ~ period + cover + sex + smoker + good_health + actuarial_age + exp + duration + capital + IMC_factor_2
  
)
```


```{r}
glm_models <- workflow_set(
  preproc = set_predictors,
  models = list(glm = glm_model)
)

glm_models
```

```{r}
glm_models <- glm_models %>%
  mutate(
    fit = map2(info,
               wflow_id,
               ~ fit(.x$workflow[[1]], insurance_train)
               )
    )

glm_models$fit[[1]]
```
















