---
title: '**Lapse: Feature Engineering**'
author: '*Roberto Jesús Alcaraz Molina*'
date: "04/05/2021"
output:
  prettydoc::html_pretty:
    theme: cayman
    df_print: paged
header-includes: 
- \usepackage{float}
- \usepackage{amsbsy}
- \usepackage{amsmath}
- \usepackage{graphicx}
- \usepackage{subfig}
- \usepackage{booktabs}
---

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      echo = T, 
                      message = FALSE,
                      fig.pos="H", 
                      fig.align="center",
                      fig.width=15,
                      cache=FALSE, error = TRUE)
```

```{r, echo = F}
# install.packages("pacman")
# devtools::install_github("stevenpawley/recipeselectors")
pacman::p_load(tidyverse, tidymodels, workflowsets, tune, patchwork, dotwhisker, doParallel, mgcv, performance, recipeselectors, vip)
theme_set(theme_bw())

# Models packages
pacman::p_load(ranger)
```

```{r}
lapse_data <- readRDS("../00_data/insurance_lapse.RDS")
lapse_data$lapse <- as.factor(lapse_data$lapse)

lapse_data <- lapse_data %>%
  filter(actuarial_age >= 21, actuarial_age <= 61)

set.seed(123)

lapse_split <- initial_split(lapse_data, prop = 0.7, strata = lapse)
lapse_train <- training(lapse_split)
lapse_test  <- testing(lapse_split)
```

In this step of the project, we will analyze the following things:

  - Variable selection through gam, drop (p-value > 0.2) and random forest.
  - Interaction between variables.
  - Preprocessing steps taking into account the EDA.
  

# Variable selection

## Recursive feature selection with Random Forest

```{r}
select_rec <- 
  recipe(lapse ~ period + cover + sex + smoker + good_health +
                   actuarial_age + duration + capital + IMC,
         data = lapse_train)

vip_model <- rand_forest() %>%
  set_engine("ranger", importance = "permutation") %>%
  set_mode("classification") %>%
  fit(lapse ~ ., data = select_rec %>% prep() %>% juice)


vip(vip_model)
```


```{r}
rfe_model <- rand_forest() %>%
  set_engine("ranger", importance = "permutation") %>%
  set_mode("classification")

# Predictive model for the deaths
set.seed(1234)
select_rec <- 
  recipe(lapse ~ cover + sex + smoker + good_health +
                   actuarial_age + duration + capital + IMC,
         data = lapse_train) %>%
  step_log(capital, IMC, base = 10) %>%
  step_select_vip(all_predictors(), outcome = "lapse", model = rfe_model, top_p = 6)

new_data <- select_rec %>% prep() %>% juice()
new_data

# The recursive feature selection with Random Forest discard the variables smoker and good_health.
```


## GAM models

```{r}
lapse_train_prep <- 
  recipe(lapse ~ cover + sex +
                   actuarial_age + duration + capital + IMC,
         data = lapse_train) %>%
  step_log(capital, IMC, base = 10) %>%
  prep() %>% juice()

gam_model_lapse <- gam(lapse ~ cover + sex +
                         s(actuarial_age, bs = "ps") +
                         s(duration, bs = "ps") +
                         s(capital, bs = "ps") + 
                         s(IMC, bs = "ps"),
                       data = lapse_train_prep, 
                       family = "binomial", 
                       method = "REML", select = F)
summary(gam_model_lapse)

# Parametric coefficients:
#              Estimate Std. Error  z value Pr(>|z|)    
# (Intercept) -1.378091   0.007555 -182.407   <2e-16 ***
# cover2      -0.035181   0.022494   -1.564    0.118    
# cover3      -0.018802   0.017630   -1.066    0.286    
# sexwoman    -0.138772   0.012218  -11.358   <2e-16 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Approximate significance of smooth terms:
#                    edf Ref.df   Chi.sq p-value    
# s(actuarial_age) 7.000  7.255   339.63  <2e-16 ***
# s(duration)      8.720  8.923 29401.84  <2e-16 ***
# s(capital)       4.304  4.917    70.14  <2e-16 ***
# s(IMC)           3.742  4.296    50.58  <2e-16 ***

gam_model_lapse <- gam(lapse ~ sex +
                         s(actuarial_age, bs = "ps") +
                         s(duration, bs = "ps") +
                         s(capital, bs = "ps") + 
                         s(IMC, bs = "ps"),
                       data = lapse_train_prep, 
                       family = "binomial", 
                       method = "REML", select = T)
summary(gam_model_lapse)

# Parametric coefficients:
#              Estimate Std. Error z value Pr(>|z|)    
# (Intercept) -1.381073   0.007145 -193.31   <2e-16 ***
# sexwoman    -0.139345   0.012203  -11.42   <2e-16 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Approximate significance of smooth terms:
#                    edf Ref.df   Chi.sq p-value    
# s(actuarial_age) 7.154      9   345.25  <2e-16 ***
# s(duration)      7.996      9 29632.71  <2e-16 ***
# s(capital)       3.459      9    69.72  <2e-16 ***
# s(IMC)           3.214      9    50.57  <2e-16 ***
# ---
```

```{r}
gam_model_lapse <- gam(lapse ~ sex +
                         s(actuarial_age, bs = "ps", by = sex) +
                         s(duration, bs = "ps", by = sex) +
                         s(capital, bs = "ps", by = sex) + 
                         s(IMC, bs = "ps", by = sex),
                       data = lapse_train_prep, 
                       family = "binomial", 
                       method = "REML", select = F)
summary(gam_model_lapse)

# Parametric coefficients:
#              Estimate Std. Error z value Pr(>|z|)    
# (Intercept) -1.366420   0.008246  -165.7   <2e-16 ***
# sexwoman    -0.159035   0.013592   -11.7   <2e-16 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Approximate significance of smooth terms:
#                             edf Ref.df    Chi.sq  p-value    
# s(actuarial_age):sexman   6.819  7.106   227.246  < 2e-16 ***
# s(actuarial_age):sexwoman 6.722  7.052   102.746  < 2e-16 ***
# s(duration):sexman        8.656  8.884 17861.417  < 2e-16 ***
# s(duration):sexwoman      8.482  8.740 11873.452  < 2e-16 ***
# s(capital):sexman         4.048  4.697    95.035  < 2e-16 ***
# s(capital):sexwoman       1.014  1.029     0.915 0.345318    
# s(IMC):sexman             3.398  4.013    42.964  < 2e-16 ***
# s(IMC):sexwoman           3.143  3.681    21.531 0.000322 ***

gam_model_lapse <- gam(lapse ~ sex +
                         s(actuarial_age, bs = "ps", by = sex) +
                         s(duration, bs = "ps", by = sex) +
                         s(capital, bs = "ps", by = sex) + 
                         s(IMC, bs = "ps", by = sex),
                       data = lapse_train_prep, 
                       family = "binomial", 
                       method = "REML", select = T)
summary(gam_model_lapse)
plot(gam_model_lapse, ylim = c(-2,2))
# Parametric coefficients:
#              Estimate Std. Error z value Pr(>|z|)    
# (Intercept) -1.365463   0.008347 -163.59   <2e-16 ***
# sexwoman    -0.172170   0.013613  -12.65   <2e-16 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Approximate significance of smooth terms:
#                               edf Ref.df    Chi.sq  p-value    
# s(actuarial_age):sexman   6.86196      9   163.275  < 2e-16 ***
# s(actuarial_age):sexwoman 5.49861      9    50.217  < 2e-16 ***
# s(duration):sexman        7.98644      9 17728.502  < 2e-16 ***
# s(duration):sexwoman      7.96828      9 11852.947  < 2e-16 ***
# s(capital):sexman         3.30700      9    96.969  < 2e-16 ***
# s(capital):sexwoman       0.02866      7     0.001 0.960642    
# s(IMC):sexman             3.67104      8    41.994  < 2e-16 ***
# s(IMC):sexwoman           1.67353      9    11.970 0.000729 ***

# saveRDS(gam_model_lapse, "../02_lapse_model/results_lapse/gam_model_lapse.RDS")
gam_model_lapse <- readRDS("../02_lapse_model/results_lapse/gam_model_lapse.RDS")
```

```{r}
# Best threshold for kappa
prob <- predict(gam_model_lapse, newdata = lapse_train_prep, 
                type = "response")

prob <- as_tibble(prob) %>%
  mutate(lapse = lapse_train$lapse)

roc_c <- prob %>%
  roc_curve(lapse, value, event_level = "second")

thresholds <- roc_c %>% select(.threshold) %>% pull()
thresholds <- quantile(thresholds, probs = seq(0.74, 0.76, 0.0001))

thresholds <- roc_c %>% select(.threshold) %>% pull()
length(which(thresholds <= 0.3272755))
thresholds <- thresholds[(193334-100):(193334+100)]
kappa <- seq(1, length(thresholds))

for (i in 1:length(thresholds)){
  confusion_matrix <- prob %>%
    mutate(pred_class = as.factor(ifelse(value > thresholds[i],
                                         "yes", "no"))) %>%
    conf_mat(truth = lapse,
             estimate = pred_class)
  
  kappa[i] <- confusion_matrix %>% 
    summary(event_level = "second") %>%
    filter(.metric == "kap") %>% 
    dplyr::select(.estimate) %>% 
    pull()
}
which.max(kappa)
thresholds[104] # 0.3272862
confusion_matrix <- prob %>%
    mutate(pred_class = as.factor(ifelse(value > thresholds[104],
                                         "yes", "no"))) %>%
    conf_mat(truth = lapse,
             estimate = pred_class)
confusion_matrix
confusion_matrix %>% 
    summary(event_level = "second") 

plot(kappa)
```


```{r}
# Best threshold for F1
prob <- predict(gam_model_lapse, newdata = lapse_train_prep, 
                type = "response")

prob <- as_tibble(prob) %>%
  mutate(lapse = lapse_train$lapse)

prec_rec_curve <- prob %>%
  pr_curve(lapse, value, event_level = "second")

autoplot(prec_rec_curve)

beta <- 1
thres <- prec_rec_curve %>%
  mutate(sum = (1 + beta^2)*(recall * precision)/((beta^2*precision) + recall)) %>%
  filter(sum == max(sum, na.rm = T)) %>%
  select(.threshold) %>%
  pull()


# thres <- 0.239206
confusion_matrix <- prob %>%
  mutate(pred_class = as.factor(ifelse(value > thres,
                                       "yes", "no"))) %>%
  conf_mat(truth = lapse,
           estimate = pred_class)

confusion_matrix
confusion_matrix %>%
  summary(event_level = "second")

prob %>%
  roc_auc(lapse, value, event_level = "second")
```

```{r}
# Best threshold for max(sensitivity + specificity)

prob <- predict(gam_model_lapse, newdata = lapse_train_prep, 
                type = "response")

prob <- as_tibble(prob) %>%
  mutate(lapse = lapse_train$lapse)

roc_c <- prob %>%
  roc_curve(lapse, value, event_level = "second")

thres <- roc_c %>%
  mutate(sum = sensitivity + specificity) %>%
  filter(sum == max(sum, na.rm = T)) %>%
  select(.threshold) %>%
  pull()

# thres <- 0.2232829
confusion_matrix <- prob %>%
  mutate(pred_class = as.factor(ifelse(value > thres,
                                       "yes", "no"))) %>%
  conf_mat(truth = lapse,
           estimate = pred_class)
confusion_matrix


confusion_matrix %>%
  summary(event_level = "second")
```

